from enum import Enum


class ResourceTypes(Enum):
    APIGW_RESTAPI = "AWS::ApiGateway::RestApi"
    APIGW_STAGE = "AWS::ApiGateway::Stage"
    APIGW_DEPLOYMENT = "AWS::ApiGateway::Deployment"
    APIGW_ACCOUNT = "AWS::ApiGateway::Account"
    APIGWV2_HTTPAPI = "AWS::ApiGatewayV2::Api"
    APIGWV2_STAGE = "AWS::ApiGatewayV2::Stage"
    CLOUDFORMATION_STACK = "AWS::CloudFormation::Stack"
    CLOUDWATCH_ALARM = "AWS::CloudWatch::Alarm"
    CLOUDWATCH_LOGS_LOGGROUP = "AWS::Logs::LogGroup"
    CLOUDWATCH_LOGS_SUBSCRIPTION_FILTER = "AWS::Logs::SubscriptionFilter"
    CODEDEPLOY_APPLICATION = "AWS::CodeDeploy::Application"
    CODEDEPLOY_DEPLOYMENT_GROUP = "AWS::CodeDeploy::DeploymentGroup"
    COGNITO_USER_POOL = "AWS::Cognito::UserPool"
    COGNITO_USER_POOL_CLIENT = "AWS::Cognito::UserPoolClient"
    LAMBDA_FUNCTION = "AWS::Lambda::Function"
    LAMBDA_PERMISSION = "AWS::Lambda::Permission"
    LAMBDA_ALIAS = "AWS::Lambda::Alias"
    LAMBDA_VERSION = "AWS::Lambda::Version"
    LAMBDA_EVENTSOURCEMAPPING = "AWS::Lambda::EventSourceMapping"
    LAMBDA_LAYER_VERSION = "AWS::Lambda::LayerVersion"
    LAMBDA_EVENT_INVOKE_CONFIG = "AWS::Lambda::EventInvokeConfig"
    S3_BUCKET = "AWS::S3::Bucket"
    IAM_ROLE = "AWS::IAM::Role"
    IAM_POLICY = "AWS::IAM::Policy"
    SNS_TOPIC = "AWS::SNS::Topic"
    SNS_SUBSCRIPTION = "AWS::SNS::Subscription"
    IOT_TOPICRULE = "AWS::IoT::TopicRule"
    EVENTS_RULE = "AWS::Events::Rule"
    KINESIS_STREAM = "AWS::Kinesis::Stream"
    DYNAMODB_TABLE = "AWS::DynamoDB::Table"
    VPC = "AWS::EC2::VPC"
    SECURITY_GROUP = "AWS::EC2::SecurityGroup"
    SUBNET = "AWS::EC2::Subnet"
    SQS_QUEUE = "AWS::SQS::Queue"
    SQS_QUEUE_POLICY = "AWS::SQS::QueuePolicy"
    KMS_KEY = "AWS::KMS::Key"
    USAGE_PLAN_KEY = "AWS::ApiGateway::UsagePlanKey"
    USAGE_PLAN = "AWS::ApiGateway::UsagePlan"
    API_KEY = "AWS::ApiGateway::ApiKey"
    RECORD_SET_GROUP = "AWS::Route53::RecordSetGroup"
    API_GW_DOMAIN_NAME = "AWS::ApiGateway::DomainName"
    API_GW_BASEPATHMAPPING = "AWS::ApiGateway::BasePathMapping"
