Parameters:
  DomainName:
    Type: String
  CertificateArn:
    Type: String
  HostedZoneId:
    Type: String

Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionUri: ${definitionuri}
      EndpointConfiguration:
        Type: REGIONAL
      Domain:
        DomainName: !Ref DomainName
        CertificateArn: !Ref CertificateArn
        EndpointConfiguration: REGIONAL
        SecurityPolicy: SecurityPolicy_TLS13_1_3_2025_09
        EndpointAccessMode: STRICT
        Route53:
          HostedZoneId: !Ref HostedZoneId

Metadata:
  SamTransformTest: true
