Parameters:
  DomainName:
    Type: String
  CertificateArn:
    Type: String
  HostedZoneId:
    Type: String

Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionUri: ${definitionuri}
      EndpointConfiguration:
        Type: EDGE
      Domain:
        DomainName: !Ref DomainName
        CertificateArn: !Ref CertificateArn
        EndpointConfiguration: EDGE
        SecurityPolicy: SecurityPolicy_TLS13_2025_EDGE
        EndpointAccessMode: STRICT
        Route53:
          HostedZoneId: !Ref HostedZoneId

Metadata:
  SamTransformTest: true
