Parameters:
  IpAddressType:
    Type: String
    Default: ipv4

Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionUri: ${definitionuri}
      EndpointConfiguration:
        Type: REGIONAL
        IpAddressType: !Ref IpAddressType
Metadata:
  SamTransformTest: true
