Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      Auth:
        DefaultAuthorizer: AWS_IAM
      StageName: my-new-stage-name
      DefinitionUri: ${definitionuri}
      Tags:
        TagKey1: TagValue1
        TagKey2: ''
Metadata:
  SamTransformTest: true
