Resources:
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs18.x
      CodeUri: ${codeuri}
      MemorySize: 128
      AutoPublishAlias: live
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins:
          - https://foo.com
          AllowMethods:
          - POST
          AllowCredentials: true
          AllowHeaders:
          - x-Custom-Header
          ExposeHeaders:
          - x-amzn-header
          MaxAge: 10
Outputs:
  FunctionUrl:
    Description: URL of the Lambda function alias
    Value: !GetAtt MyLambdaFunctionUrl.FunctionUrl
Metadata:
  SamTransformTest: true
