Resources:
  MyMicroVMImage:
    Type: AWS::Serverless::MicrovmImage
    Properties:
      Name:
        Fn::Select:
        - 2
        - Fn::Split:
          - /
          - !Ref AWS::StackId
      CodeUri: ${microvmcodeuri}
      BaseImageArn: !Sub arn:aws:lambda:${AWS::Region}:aws:microvm-image:al2023-0
      BaseImageVersion: '0'
      Resources:
      - MinimumMemoryInMiB: 512
      CpuConfigurations:
      - Architecture: ARM_64
      Hooks:
        Port: 9000
      Tags:
        Environment: IntegTest
Metadata:
  SamTransformTest: true
