Resources:
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs18.x
      CodeUri: ${codeuri}
      MemorySize: 128
      Policies:
      - AWSLambdaRole
      - AmazonS3ReadOnlyAccess
      Environment:
        Variables:
          Name: Value
          Name2: Value2
Metadata:
  SamTransformTest: true
