Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      Auth:
        DefaultAuthorizer: AWS_IAM
      StageName: MyNewStageName
      DefinitionUri: ${definitionuri}
Metadata:
  SamTransformTest: true
