Resources:
  MyWebFunction:
    Type: AWS::Serverless::WebFunction
    Properties:
      Runtime: nodejs24.x
      CodeUri: ${webfunccodeuri}
      AuthType: ApplicationManaged
      Timeout: 60
      EnvironmentVariables:
        MY_VAR: my_value
Metadata:
  SamTransformTest: true
