Resources:
  MyWebFunction:
    Type: AWS::Serverless::WebFunction
    Properties:
      Runtime: nodejs24.x
      CodeUri: ${webfunccodeuri}
      AuthType: ApplicationManaged

Outputs:
  RevisionId:
    Value: !GetAtt MyWebFunctionRevision.RevisionId
Metadata:
  SamTransformTest: true
