Resources:
  MyWebFunction:
    Type: AWS::Serverless::WebFunction
    Properties:
      Runtime: nodejs24.x
      CodeUri: ${webfunccodeuri}
      AuthType: ApplicationManaged
      EnvironmentVariables:
        MY_VAR: my_value
        ANOTHER_VAR: another_value

Outputs:
  Endpoint:
    Value: !GetAtt MyWebFunctionEndpoint.DomainName
Metadata:
  SamTransformTest: true
