Resources:
  MyWebFunction:
    Type: AWS::Serverless::WebFunction
    Properties:
      Runtime: nodejs24.x
      CodeUri: ${webfunccodeuri}
      AuthType: ApplicationManaged
      Timeout: 5
      EnvironmentVariables:
        TIMEOUT_MS: '0'

Outputs:
  Endpoint:
    Value: !GetAtt MyWebFunctionEndpoint.DomainName
Metadata:
  SamTransformTest: true
