AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  An Amazon Kinesis Firehose stream processor that converts input records from
  Apache Common Log format to JSON.
Parameters: 
  FunctionNameParameter: 
    Type: String
  TableNameParameter: 
    Type: String
Resources:
  kinesisfirehoseapachelogtojson:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      CodeUri: .
      Description: >-
        An Amazon Kinesis Firehose stream processor that converts input records
        from Apache Common Log format to JSON.
      MemorySize: 128
      Timeout: 3
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref FunctionNameParameter
        - DynamoDBCrudPolicy:
            TableName: !Ref TableNameParameter