from collections.abc import Callable
from typing import Any

from samtranslator.model import Resource

do_not_verify = {
    # type_after_transform: type_before_transform
    "AWS::Lambda::Function": "AWS::Serverless::Function",
    "AWS::Lambda::LayerVersion": "AWS::Serverless::LayerVersion",
    "AWS::Lambda::CapacityProvider": "AWS::Serverless::CapacityProvider",
    "AWS::Lambda::MicrovmImage": "AWS::Serverless::MicrovmImage",
    "AWS::Lambda::NetworkConnector": "AWS::Serverless::NetworkConnector",
    "AWS::ApiGateway::RestApi": "AWS::Serverless::Api",
    "AWS::ApiGatewayV2::Api": ["AWS::Serverless::HttpApi", "AWS::Serverless::WebSocketApi"],
    "AWS::S3::Bucket": "AWS::S3::Bucket",
    "AWS::SNS::Topic": "AWS::SNS::Topic",
    "AWS::DynamoDB::Table": "AWS::Serverless::SimpleTable",
    "AWS::CloudFormation::Stack": "AWS::Serverless::Application",
    "AWS::Cognito::UserPool": "AWS::Cognito::UserPool",
    "AWS::ApiGateway::DomainName": "AWS::ApiGateway::DomainName",
    "AWS::ApiGateway::BasePathMapping": "AWS::ApiGateway::BasePathMapping",
    "AWS::ApiGateway::DomainNameV2": "AWS::ApiGateway::DomainNameV2",
    "AWS::ApiGateway::BasePathMappingV2": "AWS::ApiGateway::BasePathMappingV2",
    "AWS::StepFunctions::StateMachine": "AWS::Serverless::StateMachine",
    "AWS::AppSync::GraphQLApi": "AWS::Serverless::GraphQLApi",
}


def verify_unique_logical_id(resource: Resource, existing_resources: dict[str, Any]) -> bool:
    """Return true if the logical id is unique."""

    # new resource logicalid exists in the template before transform
    if resource.logical_id is None or resource.logical_id not in existing_resources:
        return True
    # new resource logicalid is in  the do_not_resolve list
    return bool(
        resource.resource_type in do_not_verify
        and existing_resources[resource.logical_id]["Type"]
        in (
            do_not_verify[resource.resource_type]
            if isinstance(do_not_verify[resource.resource_type], list)
            else [do_not_verify[resource.resource_type]]
        )
    )


def is_iam_role(resource: Resource) -> bool:
    """Default scope for GeneratedLogicalIdTracker: only IAM roles are checked.

    SAM never intentionally generates the same IAM role from two different SAM resources, so any such collision is a
    bug that would silently give one resource another resource's permissions. Other resource types (e.g. shared API
    usage plans, custom domains, Route53 record set groups) ARE intentionally generated by multiple SAM resources
    under the same logical id, so they are not checked yet.
    """
    return resource.resource_type == "AWS::IAM::Role"


class GeneratedLogicalIdTracker:
    """Detects when different SAM resources generate resources with the same logical id.

    Generated resources are merged into the output template with ``dict.update()``, so without this check a later
    resource silently overwrites an earlier one with the same logical id. ``verify_unique_logical_id`` only guards
    against collisions with resources written in the input template; this class guards against collisions between
    generated resources.

    Which generated resources are checked is controlled by ``should_check``, so the scope can be widened (e.g. to all
    resource types minus an allowlist of intentionally shared logical ids) without changing the tracker or its callers.
    """

    def __init__(self, should_check: Callable[[Resource], bool] = is_iam_role) -> None:
        self._should_check = should_check
        self._sources: dict[str, str] = {}

    def record(self, resource: Resource, source_logical_id: str) -> str | None:
        """Record that ``source_logical_id`` generated ``resource``.

        :return: the logical id of a *different* SAM resource that already generated a resource with the same
            logical id, or None if there is no conflict (or the resource is out of scope).
        """
        if resource.logical_id is None or not self._should_check(resource):
            return None
        existing_source = self._sources.setdefault(resource.logical_id, source_logical_id)
        return existing_source if existing_source != source_logical_id else None
