Parameters:
  Bucket:
    Type: String
  CodeKey:
    Type: String
  SwaggerKey:
    Type: String
  ImageType:
    Type: String
    Default: image~1gif
Globals:
  Api:
    # Send/receive binary data through the APIs
    BinaryMediaTypes:
      # These are equivalent to image/gif and image/png when deployed
    - image~1jpg
    - image~1gif
    - image~1png

Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionBody:
        # Simple HTTP Proxy API
        swagger: '2.0'
        info:
          version: '2016-09-23T22:23:23Z'
          title: Simple Api
        basePath: /demo
        schemes:
        - https
        paths:
          /http/{proxy+}:
            x-amazon-apigateway-any-method:
              parameters:
              - name: proxy
                in: path
              x-amazon-apigateway-integration:
                type: http_proxy
                uri: http://httpbin.org/{proxy}
                httpMethod: ANY
                passthroughBehavior: when_no_match
                requestParameters:
                  integration.request.path.proxy: method.request.path.proxy
Metadata:
  SamTransformTest: true
