Resources:
  TriggerStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Type: EXPRESS
      Definition:
        StartAt: TryDoSomething
        States:
          TryDoSomething:
            Type: Task
            Resource: !Sub arn:${AWS::Partition}:states:::sns:publish
            Parameters:
              TopicArn: !Ref MyTopic
              Message: hello
            End: true
      Policies:
      - LambdaInvokePolicy:
          FunctionName: SomethingIsNotStateMachineFunction

  MyTopic:
    Type: AWS::SNS::Topic
    Properties:
      KmsMasterKeyId: alias/aws/sns

  MyConnector:
    Type: AWS::Serverless::Connector
    Properties:
      Source:
        Id: TriggerStateMachine
      Destination:
        Id: MyTopic
      Permissions:
      - Write
Metadata:
  SamTransformTest: true
