Parameters:
  PreCreatedMqBrokerArn:
    Type: String
  PreCreatedMqBrokerSecretArn:
    Type: String

Resources:
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs18.x
      Handler: index.handler
      CodeUri: ${codeuri}
      Events:
        MyMqEvent:
          Type: MQ
          Properties:
            Broker: !Ref PreCreatedMqBrokerArn
            Queues: [TestQueue]
            SourceAccessConfigurations:
            - Type: BASIC_AUTH
              URI: !Ref PreCreatedMqBrokerSecretArn

Metadata:
  SamTransformTest: true
