Parameters:
  PreCreatedMqBrokerArn:
    Type: String
  PreCreatedMqBrokerSecretArn:
    Type: String

Resources:
  MyLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Action: [sts:AssumeRole]
          Effect: Allow
          Principal:
            Service: [lambda.amazonaws.com]
      Policies:
      - PolicyName: IntegrationTestExecution
        PolicyDocument:
          Statement:
          - Action: [ec2:CreateNetworkInterface, ec2:CreateNetworkInterfacePermission,
              ec2:DeleteNetworkInterface, ec2:DeleteNetworkInterfacePermission, ec2:DetachNetworkInterface,
              ec2:DescribeSubnets, ec2:DescribeNetworkInterfaces, ec2:DescribeVpcs,
              ec2:DescribeInternetGateways, ec2:DescribeNetworkInterfacePermissions,
              ec2:DescribeSecurityGroups, ec2:DescribeRouteTables, logs:CreateLogGroup,
              logs:CreateLogStream, logs:PutLogEvents, kms:Decrypt, mq:DescribeBroker,
              secretsmanager:GetSecretValue]
            Effect: Allow
            Resource: '*'
      ManagedPolicyArns:
      - !Sub arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Tags:
      - {Value: SAM, Key: lambda:createdBy}

  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs18.x
      Handler: index.handler
      CodeUri: ${codeuri}
      Role: !GetAtt MyLambdaExecutionRole.Arn
      Events:
        MyMqEvent:
          Type: MQ
          Properties:
            Broker: !Ref PreCreatedMqBrokerArn
            Queues: [TestQueue]
            SourceAccessConfigurations:
            - Type: BASIC_AUTH
              URI: !Ref PreCreatedMqBrokerSecretArn

Metadata:
  SamTransformTest: true
