Resources:
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs18.x
      CodeUri: ${codeuri}
      MemorySize: 128
      Events:
        Repeat:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)
            Input: '{"Hello": "world!"}'
            Description: test schedule
            Enabled: true
            DeadLetterConfig:
              Type: SQS

Outputs:
  ScheduleName:
    Description: Name of the cw schedule
    Value:
      Ref: MyLambdaFunctionRepeat
  MyLambdaArn:
    Description: Arn of the lambda target
    Value:
      Fn::GetAtt:
      - MyLambdaFunction
      - Arn
  MyDLQArn:
    Description: Arn of the dead-letter queue created for the Schedule rule target
    Value:
      Fn::GetAtt:
      - MyLambdaFunctionRepeatQueue
      - Arn
  MyDLQUrl:
    Description: Url of the dead-letter queue created for the Schedule rule target
    Value:
      Ref: MyLambdaFunctionRepeatQueue
Metadata:
  SamTransformTest: true
