Parameters:
  PreCreatedMskClusterArn:
    Type: String

Resources:
  MyMskStreamProcessor:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs18.x
      Handler: index.handler
      CodeUri: ${codeuri}
      Events:
        MyMskEvent:
          Type: MSK
          Properties:
            Enabled: false
            StartingPosition: LATEST
            Stream:
              Ref: PreCreatedMskClusterArn
            Topics:
            - MyDummyTestTopic

Metadata:
  SamTransformTest: true
