Globals:
  HttpApi:
    CorsConfiguration:
      AllowHeaders:
      - x-apigateway-header
      AllowMethods:
      - GET
      AllowOrigins:
      - https://foo.com
      ExposeHeaders:
      - x-amzn-header

Resources:
  HttpApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      InlineCode: |
        exports.handler = async (event) => {
          return {
          statusCode: 200,
          body: JSON.stringify(event),
          headers: {}
          }
        }
      Handler: index.handler
      Runtime: nodejs18.x
      Events:
        ImplicitApi:
          Type: HttpApi
          Properties:
            Method: GET
            Path: /path
            TimeoutInMillis: 15000
            PayloadFormatVersion: '1.0'

Outputs:
  ApiUrl:
    Description: URL of your API endpoint
    Value:
      Fn::Sub: https://${ServerlessHttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/
  ApiId:
    Description: Api id of ServerlessHttpApi
    Value:
      Ref: ServerlessHttpApi
Metadata:
  SamTransformTest: true
