# Must support explicit bucket, key and version in CodeUri and DefinitionUri parameters

Parameters:
  Bucket:
    Type: String
  CodeKey:
    Type: String
  SwaggerKey:
    Type: String

Resources:

  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs18.x
      Handler: index.handler
      MemorySize: 128
      CodeUri:
        Bucket:
          Ref: Bucket
        Key:
          Ref: CodeKey


  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: FancyName
      DefinitionUri:
        Bucket:
          Ref: Bucket
        Key:
          Ref: SwaggerKey

Metadata:
  SamTransformTest: true
