Parameters:
  DisableSchemaValidationValue:
    Type: String
    AllowedValues: ['true', 'false']

Resources:
  ConnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      InlineCode: |
        print("hello")
      Runtime: nodejs24.x
  MyApi:
    Type: AWS::Serverless::WebSocketApi
    Properties:
      DisableSchemaValidation: true
      Name: MyApi
      RouteSelectionExpression: $request.body.action
      Routes:
        $connect:
          FunctionArn: !GetAtt ConnectFunction.Arn
Outputs:
  ApiId:
    Value: !Ref MyApi
Metadata:
  SamTransformTest: true
