AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  Deploy this lambda to a Greengrass core where it will send a hello world
  message to a topic
Resources:
  greengrasshelloworld:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: greengrassHelloWorld.function_handler
      Runtime: python2.7
      CodeUri: .
      Description: >-
        Deploy this lambda to a Greengrass core where it will send a hello world
        message to a topic
      MemorySize: 128
      Timeout: 3
