import itertools
from unittest.mock import patch

from parameterized import parameterized

from tests.plugins.application.test_serverless_app_plugin import mock_get_region
from tests.translator.test_translator import mock_sar_service_call, TestTranslatorEndToEnd


class TestResourceLevelAttributes(TestTranslatorEndToEnd):
    @parameterized.expand(
        itertools.product(
            [
                "cognito_userpool_with_event",
                "s3_with_condition",
                "function_with_condition",
                "basic_function",
                "basic_function_withimageuri",
                "basic_application",
                "application_preparing_state",
                "application_with_intrinsics",
                "cloudwatchevent",
                "eventbridgerule",
                "eventbridgerule_with_dlq",
                "eventbridgerule_with_retry_policy",
                "eventbridgerule_schedule_properties",
                "cloudwatch_logs_with_ref",
                "cloudwatchlog",
                "streams",
                "sqs",
                "function_with_amq",
                "function_with_amq_kms",
                "simpletable",
                "simpletable_with_sse",
                "implicit_api",
                "explicit_api",
                "api_description",
                "api_endpoint_configuration",
                "api_endpoint_configuration_with_vpcendpoint",
                "api_with_auth_all_maximum",
                "api_with_auth_all_minimum",
                "api_with_auth_no_default",
                "api_with_auth_with_default_scopes",
                "api_with_auth_with_default_scopes_openapi",
                "api_with_default_aws_iam_auth",
                "api_with_default_aws_iam_auth_and_no_auth_route",
                "api_with_method_aws_iam_auth",
                "api_with_aws_iam_auth_overrides",
                "api_with_method_settings",
                "api_with_binary_media_types",
                "api_with_binary_media_types_definition_body",
                "api_with_minimum_compression_size",
                "api_with_resource_refs",
                "api_with_cors",
                "api_with_cors_and_auth_no_preflight_auth",
                "api_with_cors_and_auth_preflight_auth",
                "api_with_cors_and_only_methods",
                "api_with_cors_and_only_headers",
                "api_with_cors_and_only_origins",
                "api_with_cors_and_only_maxage",
                "api_with_cors_and_only_credentials_false",
                "api_with_cors_no_definitionbody",
                "api_with_incompatible_stage_name",
                "api_with_gateway_responses",
                "api_with_gateway_responses_all",
                "api_with_gateway_responses_minimal",
                "api_with_gateway_responses_implicit",
                "api_with_gateway_responses_string_status_code",
                "api_cache",
                "api_with_access_log_setting",
                "api_with_canary_setting",
                "api_with_xray_tracing",
                "api_request_model",
                "api_with_stage_tags",
                "s3",
                "s3_create_remove",
                "s3_existing_lambda_notification_configuration",
                "s3_existing_other_notification_configuration",
                "s3_filter",
                "s3_multiple_events_same_bucket",
                "s3_multiple_functions",
                "s3_with_dependsOn",
                "sns",
                "sns_sqs",
                "sns_existing_sqs",
                "sns_outside_sqs",
                "sns_existing_other_subscription",
                "sns_topic_outside_template",
                "alexa_skill",
                "alexa_skill_with_skill_id",
                "iot_rule",
                "layers_with_intrinsics",
                "layers_all_properties",
                "function_managed_inline_policy",
                "unsupported_resources",
                "intrinsic_functions",
                "basic_function_with_tags",
                "depends_on",
                "function_event_conditions",
                "function_with_dlq",
                "function_with_kmskeyarn",
                "function_with_alias",
                "function_with_alias_intrinsics",
                "function_with_alias_and_event_sources",
                "function_with_resource_refs",
                "function_with_global_layers",
                "function_with_layers",
                "function_with_many_layers",
                "function_with_permissions_boundary",
                "function_with_policy_templates",
                "function_with_sns_event_source_all_parameters",
                "function_with_conditional_managed_policy",
                "function_with_conditional_managed_policy_and_ref_no_value",
                "function_with_conditional_policy_template",
                "function_with_conditional_policy_template_and_ref_no_value",
                "function_with_request_parameters",
                "function_with_signing_profile",
                "global_handle_path_level_parameter",
                "globals_for_function",
                "globals_for_api",
                "globals_for_simpletable",
                "all_policy_templates",
                "simple_table_ref_parameter_intrinsic",
                "simple_table_with_table_name",
                "function_concurrency",
                "simple_table_with_extra_tags",
                "explicit_api_with_invalid_events_config",
                "no_implicit_api_with_serverless_rest_api_resource",
                "implicit_api_deletion_policy_precedence",
                "implicit_api_with_serverless_rest_api_resource",
                "implicit_api_with_auth_and_conditions_max",
                "implicit_api_with_many_conditions",
                "implicit_and_explicit_api_with_conditions",
                "inline_precedence",
                "api_with_cors_and_conditions_no_definitionbody",
                "api_with_auth_and_conditions_all_max",
                "api_with_apikey_default_override",
                "api_with_apikey_required",
                "api_with_path_parameters",
                "function_with_event_source_mapping",
                "function_with_event_dest",
                "function_with_event_dest_basic",
                "function_with_event_dest_conditional",
                "api_with_usageplans",
                "api_with_usageplans_intrinsics",
                "state_machine_with_inline_definition",
                "state_machine_with_tags",
                "state_machine_with_inline_definition_intrinsics",
                "state_machine_with_role",
                "state_machine_with_inline_policies",
                "state_machine_with_sam_policy_templates",
                "state_machine_with_definition_S3_string",
                "state_machine_with_definition_S3_object",
                "state_machine_with_definition_substitutions",
                "state_machine_with_standard_logging",
                "state_machine_with_express_logging",
                "state_machine_with_managed_policy",
                "state_machine_with_condition",
                "state_machine_with_schedule",
                "state_machine_with_schedule_dlq_retry_policy",
                "state_machine_with_cwe",
                "state_machine_with_eb_retry_policy",
                "state_machine_with_eb_dlq",
                "state_machine_with_eb_dlq_generated",
                "state_machine_with_explicit_api",
                "state_machine_with_implicit_api",
                "state_machine_with_implicit_api_globals",
                "state_machine_with_api_authorizer",
                "state_machine_with_api_authorizer_maximum",
                "state_machine_with_api_resource_policy",
                "state_machine_with_api_auth_default_scopes",
                "state_machine_with_condition_and_events",
                "state_machine_with_xray_policies",
                "state_machine_with_xray_role",
                "function_with_file_system_config",
                "state_machine_with_permissions_boundary",
            ],
            [
                ("aws", "ap-southeast-1"),
                ("aws-cn", "cn-north-1"),
                ("aws-us-gov", "us-gov-west-1"),
            ],  # Run all the above tests against each of the list of partitions to test against
        )
    )
    @patch(
        "samtranslator.plugins.application.serverless_app_plugin.ServerlessAppPlugin._sar_service_call",
        mock_sar_service_call,
    )
    @patch("botocore.client.ClientEndpointBridge._check_default_region", mock_get_region)
    def test_transform_with_additional_resource_level_attributes(self, testcase, partition_with_region):
        partition = partition_with_region[0]
        region = partition_with_region[1]

        # add resource level attributes to input resources
        manifest = self._read_input(testcase)
        resources = manifest.get("Resources", [])
        for _, resource in resources.items():
            resource["DeletionPolicy"] = "Delete"
            resource["UpdateReplacePolicy"] = "Retain"

        # add resource level attributes to expected output resources
        expected = self._read_expected_output(testcase, partition)
        expected_resources = expected.get("Resources", [])
        for _, expected_resource in expected_resources.items():
            expected_resource["DeletionPolicy"] = "Delete"
            expected_resource["UpdateReplacePolicy"] = "Retain"

        self._compare_transform(manifest, expected, partition, region)
