AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A function triggered on a timer.
Resources:
  ScheduledFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: s3://<bucket>/schedule.zip
      Events:
        Timer:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)