AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  Creates LogicMonitor OpsNotes for CloudWatch Events, thereby enabling
  correlation between events and performance data.
Resources:
  logicmonitorsendcloudwatchevents:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python2.7
      CodeUri: .
      Description: >-
        Creates LogicMonitor OpsNotes for CloudWatch Events, thereby enabling
        correlation between events and performance data.
      MemorySize: 128
      Timeout: 30
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'kms:Decrypt'
              Resource: '*'
      Environment:
        Variables:
          ACCOUNT_NAME: <enter value here>
          API_ACCESS_ID: <enter value here>
          API_ACCESS_KEY: <enter value here>
