AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  Uses ImageMagick to perform simple image processing operations, such as resizing.
Metadata:
  Name: imageprocessingservice
Parameters: 
    IdentityNameParameter: 
      Type: String
Resources:
  imageprocessingservice:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs4.3
      CodeUri: .
      Description: >-
        Uses ImageMagick to perform simple image processing operations, such as resizing.
      MemorySize: 512
      Timeout: 30
      Policies:
        - SESSendBouncePolicy:
            IdentityName: !Ref IdentityNameParameter
